-   id: dansabel-all
    name: dansabel-all
    description: Checks and lints Ansible projects
    entry: pre-commit.sh
    language: script

-   id: dansabel-ansible
    name: dansabel-ansible
    description: Checks and lints Ansible projects (YAML/Jinja2 only)
    entry: jinjalint.py
    language: script
    types: [file]
    files: (\.yml|\.j2)$|/templates/.*
